name = "sec-pickem"
main = "src/worker.js"
compatibility_date = "2024-09-23"

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "sec-pickem-db"
database_id = "0bf0724f-ae3b-43b1-af11-1cae0b7b21c2"
